[project]
name = "motrixarena-vbot-rl"
version = "0.1.0"
description = "PPO-based VBot quadruped navigation project for MotrixArena Competition S1"
requires-python = "==3.10.*"

[project.optional-dependencies]
docs = [
    "sphinx",
    "autodocsumm",
    "pydata-sphinx-theme",
    "myst-parser",
    "sphinx-copybutton",
    "sphinx-subfigure",
    "sphinxcontrib-video",
    "sphinx-togglebutton",
    "sphinx-design",
]

[tool.uv.workspace]
members = ["motrix_envs", "motrix_rl"]

[tool.uv]
package = false

# for ReadtheDocs
[tool.setuptools]
packages = ["motrix_envs", "motrix_rl"]
